[package]
name = "automata-build-script"
version = "0.1.0"
edition = "2021"
authors = ["Automata Team"]
homepage = "https://www.ata.network/"

[features]
tstd_app = []

[dependencies]
cc = { version = "1.1.5" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8.19"